# If true, additional diagnostic information
# will be printed to stderr.
verbose = true

# If given, ipsets will be saved when gerberos is
# terminated (unless killed by SIGKILL) and 
# restored when gerberos starts. Timeouts will
# be restored as saved.
saveFilePath = "./gerberos.save"

[rules]
    [rules.apache-fuzzing]
    # Required. Available sources are
    # - ["file", "<path to non-directory file>"]
    # - ["systemd", "<name of systemd service>"]
    source = ["file", "/var/log/apache2/access.log"]
    # Required. "%host%" must appear exactly once in
    # each regexp. It will be replaced with a subexpression
    # named "host" matching IPv4 and IPv6 addresses.
    # Please avoid using "x*", as this may match
    # part of the host. Use "x*?" instead.
    regexp = ["%host%.*?40(0|8) 0 \"-\" \"-\""]
    # Required. Available actions are
    # - ["ban", "<value parsable by time.ParseDuration>"]
    # - ["log"]
    action = ["ban", "1h"]
    # Optional. In this case, the action will be triggered
    # once the same match has occurred 5 times within 10 
    # seconds, resetting the counter.
    occurrences = ["5", "10s"]

    [rules.sshd-invalid-user]
    source = ["file", "/var/log/auth.log"]
    regexp = ["Invalid user.*?%host%"]
    action = ["ban", "24h"]
